### ISSUE TITLE
Upstream into lld

### ISSUE THREAD

**Issue by ElvishJerricco** [alexcrichton/wasm-gc#1]
~~There is some ongoing work to produce a proper port of LLD for WebAssembly over at https://github.com/WebAssembly/lld/tree/wasm.~~ The wasm linker is now being upstreamed, and exists in the latest checkout of lld. Would be great to have this there as the `--gc-sections` argument.

**Comment by alexcrichton** [comment]
I'm going to close this as this is upstream in LLD
