### ISSUE TITLE
Panic with externs that have u64 and *mut in params

### ISSUE THREAD

**Issue by gavofyork** [alexcrichton/wasm-gc#11]
Don't really known how to describe it other than "it panics with some innocuous-looking code". Here's some code; it's about as simple as I can make it to demonstrate the error:

```
#![no_std]
#![feature(lang_items)]
#[lang = "panic_fmt"]
fn panic_fmt() -> ! {
	  loop {}
}
extern "C" {
	fn ext_memcpy(dest: *mut u8, src: *const u8, n: usize) -> *mut u8;
	fn ext_memmove(dest: *mut u8, src: *const u8, n: usize) -> *mut u8;
}
#[no_mangle]
pub unsafe extern "C" fn memcpy(dest: *mut u8, src: *const u8, n: usize) -> *mut u8 {
	ext_memcpy(dest, src, n)
}
#[no_mangle]
pub unsafe extern "C" fn memmove(dest: *mut u8, src: *const u8, n: usize) -> *mut u8 {
	ext_memmove(dest, src, n)
}

extern "C" {
	fn imported(number: u64);
}

/// Test some execution.
#[no_mangle]
pub fn test(i: u64) {
	unsafe { imported(i) }
}
```

Compiling with target `wasm32-unknown-unknown` works fine. Running `wasm-gc` on it results in:

```
thread 'main' panicked at 'assertion failed: *i != u32::max_value()', /Users/gav/.cargo/git/checkouts/wasm-gc-d84f174ed78190a0/7b85e0f/src/main.rs:610:8
```

Removing any one of the three (non-panic) functions results in the error going away.

**Comment by alexcrichton** [comment]
Thanks for the report! I think this is happening because this crate automatically gc's intrinsics like memcpy/memmove and that's causing it to go awry. I'm not sure why the panic is happening though...
