### ISSUE TITLE
Move wasm-gc into a library crate

### ISSUE THREAD

**Issue by koute** [alexcrichton/wasm-gc#12]
It would be really nice to have this as a library crate.

I started using wasm-gc in my [cargo-web](https://github.com/koute/cargo-web), and for now I've just [copy and pasted it into my own repository](https://github.com/koute/cargo-web/blob/master/src/wasm_gc.rs). I'd love to get rid of it and just grab a crate off crates.io (:

**Comment by alexcrichton** [comment]
Sounds plausible to me! I'd be more than willing to have a PR to separate and could then publish.

**Comment by koute** [comment]
Created a PR here: https://github.com/alexcrichton/wasm-gc/pull/13 (:
