### ISSUE TITLE
Edge case: Does not install correctly on WSL (Windows Subsystem for Linux)

### ISSUE THREAD

**Issue by selfup** [alexcrichton/wasm-gc#5]
### Command executed

`wasm-gc main.wasm builds/small-main.wasm --verbose`

### Last step where the failure occurs (`--verbose`)

Compiling wasm-gc v0.1.0 (https://github.com/alexcrichton/wasm-gc#6fe4e9de)
     Running `rustc --crate-name wasm_gc /home/selfup/.cargo/git/checkouts/wasm-gc-d84f174ed78190a0/6fe4e9d/src/main.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=220fb6710333d060 -C extra-filename=-220fb6710333d060 --out-dir /tmp/cargo-install.7Apv5JBDnXQf/release/deps -L dependency=/tmp/cargo-install.7Apv5JBDnXQf/release/deps --extern env_logger=/tmp/cargo-install.7Apv5JBDnXQf/release/deps/libenv_logger-00e3003c8ba14f89.rlib --extern parity_wasm=/tmp/cargo-install.7Apv5JBDnXQf/release/deps/libparity_wasm-353ddb98eb2b0520.rlib --extern log=/tmp/cargo-install.7Apv5JBDnXQf/release/deps/liblog-b8bca32e3b1fbf3b.rlib --cap-lints allow`
error: could not exec the linker `cc`: No such file or directory (os error 2)
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/selfup/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/tmp/cargo-install.7Apv5JBDnXQf/release/deps/wasm_gc-220fb6710333d060.wasm_gc0.rcgu.o" "-o" "/tmp/cargo-install.7Apv5JBDnXQf/release/deps/wasm_gc-220fb6710333d060" "/tmp/cargo-install.7Apv5JBDnXQf/release/deps/wasm_gc-220fb6710333d060.crate.allocator.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-nodefaultlibs" "-L" "/tmp/cargo-install.7Apv5JBDnXQf/release/deps" "-L" "/home/selfup/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/cargo-install.7Apv5JBDnXQf/release/deps/libenv_logger-00e3003c8ba14f89.rlib" "/tmp/cargo-install.7Apv5JBDnXQf/release/deps/libparity_wasm-353ddb98eb2b0520.rlib" "/tmp/cargo-install.7Apv5JBDnXQf/release/deps/libbyteorder-3088e227f96eed4c.rlib" "/tmp/cargo-install.7Apv5JBDnXQf/release/deps/liblog-b8bca32e3b1fbf3b.rlib" "/tmp/cargo-install.7Apv5JBDnXQf/release/deps/libparking_lot-983789a352d7dd79.rlib" "/tmp/cargo-install.7Apv5JBDnXQf/release/deps/libowning_ref-b0ac86dab5cfa5b4.rlib" "/tmp/cargo-install.7Apv5JBDnXQf/release/deps/libstable_deref_trait-33a4ea7853d971e7.rlib" "/tmp/cargo-install.7Apv5JBDnXQf/release/deps/libparking_lot_core-9f87afe6dffcdf4e.rlib" "/tmp/cargo-install.7Apv5JBDnXQf/release/deps/librand-4448adbdcf79d3b7.rlib" "/tmp/cargo-install.7Apv5JBDnXQf/release/deps/libsmallvec-41895afb1a75c272.rlib" "/tmp/cargo-install.7Apv5JBDnXQf/release/deps/liblibc-a12f8fa54a53769e.rlib" "/home/selfup/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-cc8b303e3403a89b.rlib" "/home/selfup/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-7ea6f64ea02051fd.rlib" "/home/selfup/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-f1fba9b54042d271.rlib" "/home/selfup/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-46a427bcbb71fa34.rlib" "/home/selfup/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_system-afe41ccc67b2a14a.rlib" "/home/selfup/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-aac5870ffe4fa74c.rlib" "/home/selfup/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-6a8e7eff29b6cad2.rlib" "/home/selfup/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_unicode-a768e53a3f571290.rlib" "/home/selfup/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-016e6e96bb6127b9.rlib" "/home/selfup/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-f2b084cc7a7d8bb1.rlib" "-Wl,-Bdynamic" "-l" "util" "-l" "util" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util" "-l" "util"

error: aborting due to previous error

error: failed to compile `wasm-gc v0.1.0 (https://github.com/alexcrichton/wasm-gc#6fe4e9de)`, intermediate artifacts can be found at `/tmp/cargo-install.7Apv5JBDnXQf`

Caused by:
  Could not compile `wasm-gc`.

Caused by:
  process didn't exit successfully: `rustc --crate-name wasm_gc /home/selfup/.cargo/git/checkouts/wasm-gc-d84f174ed78190a0/6fe4e9d/src/main.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=220fb6710333d060 -C extra-filename=-220fb6710333d060 --out-dir /tmp/cargo-install.7Apv5JBDnXQf/release/deps -L dependency=/tmp/cargo-install.7Apv5JBDnXQf/release/deps --extern env_logger=/tmp/cargo-install.7Apv5JBDnXQf/release/deps/libenv_logger-00e3003c8ba14f89.rlib --extern parity_wasm=/tmp/cargo-install.7Apv5JBDnXQf/release/deps/libparity_wasm-353ddb98eb2b0520.rlib --extern log=/tmp/cargo-install.7Apv5JBDnXQf/release/deps/liblog-b8bca32e3b1fbf3b.rlib --cap-lints allow` (exit code: 101)

***

Not really sure this needs to be worried about. Works fine on native Windows/Linux/macOS just not WSL. Maybe have a little warning? 😄

**Comment by alexcrichton** [comment]
Thanks for the report! The error here is -- 

```
 error: could not exec the linker cc: No such file or directory (os error 2)
```

I think that means you need to install the `gcc` package in WSL?

**Comment by selfup** [comment]
That makes sense! Maybe I can update the README for WSL? Otherwise you can as well 😄

**Comment by selfup** [comment]
Comment in question:

https://github.com/alexcrichton/wasm-gc/pull/6#issuecomment-347740271

**Comment by selfup** [comment]
Closing - because resolved 🚀
