### ISSUE TITLE
Crashes on wasm_import_memory modules

### ISSUE THREAD

**Issue by Arnavion** [alexcrichton/wasm-gc#9]
wasm-gc panics with [`no memory section`](https://github.com/alexcrichton/wasm-gc/blob/7b85e0fb/src/main.rs#L228) when run on a module that has:

```rust
#![feature(wasm_import_memory)]
#![wasm_import_memory]
```

Such a module imports memory as `env.memory` (eg `(import "env" "memory" (memory $env.memory 17))`) instead of exporting it (eg `(memory $memory (export "memory") 17)`). It manifests as an `ImportEntry` in `import_sections`: `ImportEntry { module_str: "env", field_str: "memory", external: Memory(MemoryType(ResizableLimits { initial: 17, maximum: None })) }`

**Comment by alexcrichton** [comment]
Heh yeah I've run into this from time to time and just haven't had a chance to fix it yet! I suspect there's just a stray unwrap somewhere or something like that which should be easy enough to remove.

**Comment by Arnavion** [comment]
The unwrap location is not a mystery - I linked it in the OP. The issue is that the code assumes in a few different ways that memory is an export and all imports are functions.

For example `LiveContext::add_function` assumes any index that belongs to an import entry is an imported function, even when the index points to an imported memory and is actually the index of an internal function (should compare against `ImportSection.functions()` instead of `ImportSection.entries().len()`, which requires bumping the `parity-wasm` dep in `Cargo.lock`).

I'm fixing these as I go along.

**Comment by alexcrichton** [comment]
Oh awesome! I'd happily take a look at a PR to fix this up :)
